package com.denis.georgiatransit.shared.presentation.ui.automation

object AutomationId {
    const val SplashLoading = "splash.loading"
    const val SplashError = "splash.error"
    const val SplashRetry = "splash.retry"
    const val CityScreen = "city-selection.screen"
    const val CityTbilisi = "city-selection.tbilisi"
    const val CityBatumi = "city-selection.batumi"
    const val CityContinue = "city-selection.continue"
    const val CityLocation = "city-selection.location"
    const val MapScreen = "map.screen"
    const val MapRoutes = "map.routes"
    const val MapChangeCity = "map.change-city"
    const val MapMyLocation = "map.my-location"
    const val MapLocationSettings = "map.location-settings"
    const val MapUserLocation = "map.user-location"
    const val RoutesScreen = "routes.screen"
    const val RoutesOption = "routes.option"
    const val RoutesLoading = "routes.loading"
    const val RoutesError = "routes.error"
    const val RoutesRetry = "routes.retry"
    const val RoutesBack = "routes.back"
    const val RoutesConfirm = "routes.confirm"
}
